// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiSvg7HIaqUC-DhXmVP7NfP8J78ERpq4Y',
    appId: '1:790189508500:web:0e2b8769d7d037f052b181',
    messagingSenderId: '790189508500',
    projectId: 'bento-app-ff69f',
    authDomain: 'bento-app-ff69f.firebaseapp.com',
    storageBucket: 'bento-app-ff69f.firebasestorage.app',
    measurementId: 'G-M130GN6N13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAexAlzasWng_GIT5Hln2fxnRJt2BgLjqE',
    appId: '1:790189508500:android:a33f59c35f9ec8d352b181',
    messagingSenderId: '790189508500',
    projectId: 'bento-app-ff69f',
    storageBucket: 'bento-app-ff69f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQSODlpMUZe6YRekRWV1tlX-B_9RGCSO8',
    appId: '1:790189508500:ios:4aa054a3fb6084d752b181',
    messagingSenderId: '790189508500',
    projectId: 'bento-app-ff69f',
    storageBucket: 'bento-app-ff69f.firebasestorage.app',
    iosBundleId: 'com.example.bentoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQSODlpMUZe6YRekRWV1tlX-B_9RGCSO8',
    appId: '1:790189508500:ios:4aa054a3fb6084d752b181',
    messagingSenderId: '790189508500',
    projectId: 'bento-app-ff69f',
    storageBucket: 'bento-app-ff69f.firebasestorage.app',
    iosBundleId: 'com.example.bentoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiSvg7HIaqUC-DhXmVP7NfP8J78ERpq4Y',
    appId: '1:790189508500:web:552f0cca693418d952b181',
    messagingSenderId: '790189508500',
    projectId: 'bento-app-ff69f',
    authDomain: 'bento-app-ff69f.firebaseapp.com',
    storageBucket: 'bento-app-ff69f.firebasestorage.app',
    measurementId: 'G-TEN17X6ME6',
  );
}
